### ISSUE TITLE
Suggestion: Use pre-commit hook to run rustfmt

### ISSUE THREAD

**Issue by madig** [linebender/kurbo#1]
> Also rustfmt again. I need to do that before every commit...

Have a look at https://pre-commit.com/, maybe https://github.com/doublify/pre-commit-rust is helpful. You use the CLI application to install a hook to run rustfmt before every commit and it will shout at you and format the file for you if you forget to do it manually.

Also: https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server

**Comment by raphlinus** [comment]
Thanks for the suggestion! I've added pre-commit manually, and also set up Travis. I think that should take care of it going forward.
