### ISSUE TITLE
CubicBez::arclen precision changed for tiny curves after v0.6

### ISSUE THREAD

**Issue by RazrFalcon** [linebender/kurbo#122]
```rust
let c = kurbo::CubicBez::from_points(0.2, 0.73, 0.35, 1.08, 0.85, 1.08, 1.0, 0.73);
println!("{}", c.arclen(1.0));
```

- v0.5.11 - `1.0148235222271658`
- v0.6.1 - `0.8`

Is this is an expected behavior? 

PS: on regular/large curves this is unnoticeable.

**Comment by raphlinus** [comment]
This seems to be a natural consequence of #100, which fixes a problem with degenerate behavior by special-casing short lines. The result is still within tolerance, so I'm not yet convinced this is actually a bug.

**Comment by RazrFalcon** [comment]
Looks like by increasing the accuracy to 0.5 I can get the old result back. Not sure how it affects the performance, but it isn't that important in my case.

So I guess we can close this, since this is an expected result.
