### ISSUE TITLE
Converting iterator of path elements to segments

### ISSUE THREAD

**Issue by laurmaedje** [linebender/kurbo#136]
There is currently no built-in way to transform an iterator of path elements to an iterator of path segments. My use case is to take an argument of type `impl Shape` and to iterate over its segments. `Shape::to_bez_path` only returns an iterator over path elements. I could, of course, collect into a `BezPath` and the call `segments()` on that, but I'd like to avoid the intermediate allocation.

Looking into the source code, there is the private function `BezPath::segments_of_slice`, which has a todo that it should maybe be public, and there is the underlying `BezPathSegs` iterator. Unfortunately, `segments_of_slice` still wouldn't work with general iterators. 

To fix this, how about adding a freestanding function like this:
```rust
pub fn segments(path: impl IntoIterator<Item = PathEl>) -> impl Iterator<Item = PathSeg> { ... }
```
This function would be nicely parallel to `flatten` and could similarly link to `BezPath::segments`, which would then be implemented in terms of it. `segments_of_slice` could then be removed, I think.

If you think this sounds like a good way to do it, I'd be happy to open a PR!

(An alternative, also stated in `segments_of_slice`'s comment, would be to create a trait such that `iter.segments()` works on any iterator. Personally, I think this wouldn't be worth it and the parallelity with `flatten` would also be lost.)

**Comment by cmyr** [comment]
I think this makes sense. In terms of the implementation, couldn't we add a `segments` method to `Shape`, and have a default impl that just wraps `to_bez_path`? This could be backed by a public helper method in case the user wanted to iterate the segments of a sequence of `PathEl` that wasn't a `Shape`.

Looking at the `Shape` trait again, the api nerd in me really thinks that `to_bez_path` should be renamed `iter_bezier_elements` or `iter_elements` or `bezier_elements`, and then a separate `to_bezier` method should return a constructed `BezPath`. 🤷

**Comment by laurmaedje** [comment]
Adding it to `Shape` sounds good to me. I agree that the naming of `to_bez_path` is confusing, I tripped over this multiple times. If we would rename `to_bez_path`, I think both methods should be named similarly, like `elements` and `segments` or `iter_elements` and `iter_segments`.

**Comment by cmyr** [comment]
yes, I agree. I also think this can be done in a pretty painless way, by marking `to_bez_path` and `into_bez_path` as deprecated, adding `elements` and `segments`, and then adding a new `to_bezpath` or `to_bezier` method that returns a `BezPath`. It's the name of this latter method that I'm unsure about.

**Comment by laurmaedje** [comment]
I think `to_bezpath` or `to_path` are pretty reasonable choices, considering that the method returns a `BezPath`. I don't like `to_bezier` all too much because there is no type called `Bezier` and it's also not clear that it is a _path_ of bezier curves and not a single curve.

**Comment by laurmaedje** [comment]
I think there are a couple of problems here in terms of implementation.

1. If we deprecate `to_bez_path`, `into_bez_path` (and probably also `BezPathIter`) and replace them with `elements`, `to_bezpath` and `ElementsIter`, even with deprecation this would be breaking because one would need to be implemented in terms of the other and (1) implementing `to_bez_path` through `elements` would force users to implement `elements` while (2) implementing `elements` through `to_bez_path` would force users to implement a deprecated item. I don't see how to fix this apart from simply renaming the items (instead of deprecating) and accepting the breakage.
2. If we add `segments` in terms of `elements`, the freestanding `segments` function can't return an abstract `impl Iterator<Item = PathSeg>` because we need to _name_ the return type in the trait. Also, associated type defaults are unstable, so we can't do `fn segments(&self) -> Self::SegmentsIter { ... }` and `type SegmentsIter: Iterator<Item = PathSeg> = MyIter<Self::ElementsIter>`, but would have to name the iterator directly in `segments`' return type (and it would need to be public). Fixing the type would make it basically impossible to override the method (but then again, I also don't see a real reason to override it).

I don't see a really clear path forward, here.

**Comment by cmyr** [comment]
I think the following works?

- keep the `BezPathIter` type.
- add an `elements` method, that is exactly `to_bez_path`.
- deprecate `to_bez_path`, and have the implementation call `elements`.
- add a top-level type, `Segments<T>`. have an `impl<T: Iterator<Item=PathEl>> Iterator<PathSeg> for Segments<T>>`.
- add a method to `Shape`, `fn segments(&self) -> Segments<Self::BezPathIter>`.
- add `fn to_path(&self) -> BezPath` that calls `self.elements().collect()`
- deprecate `into_bez_path`.

It's very possible I'm missing something, but I *think* this gets us where we want to be.

**Comment by laurmaedje** [comment]
I think this would work, but still be a breaking change because even though _users_ of `Shape` can transparently use `elements` or `to_bez_path`, _implementors_ of `Shape` would get an error because the mandatory method `elements` is missing. If you are fine with this breakage, it would be okay.

**Comment by cmyr** [comment]
fair point. Another option would be to keep the `to_bez_path` impls in place, and actually call into that from an `elements` auto-impl? Which we could maybe mark `#[allow(deprecated)]` or something? This is starting to get a bit gymnastic, maybe.

**Comment by laurmaedje** [comment]
Do you mean keep `to_bez_path` mandatory, deprecate it and basically add an `elements` alias? Then, users would still be forced to implement that deprecated method.

I think, there are basically two options:
- Accept breakage, rename everything and depart to kurbo `0.7`.
- Keep everything, deprecate nothing, create the freestanding `segments` function and
    - optionally add `segments` to `Shape`
    - very optionally add `elements` as an alias for `to_bez_path`

There is also the thing that `BezPath::segments` exists, which would not be needed anymore with `Shape` having `segments`. This could, however, be deprecated unbreakingly if `Shape::segments` gets added (I think).

**Comment by raphlinus** [comment]
I don't understand all implications of the current proposal, but I wouldn't worry too much about deprecation and breakage. Semver takes care of us if we move to 0.7, and I don't think there's a lot that would be seriously inconvenienced by a change. We should focus on getting the right behavior.

Some of current status of kurbo is a *bit* placeholder, as I think there's more that could be done with non-boxing, non-allocating iterators if and when GAT lands. Again, whether this intersects with that issue isn't something I've deeply considered, just mentioning it for context.

**Comment by laurmaedje** [comment]
Then, I would propose the following:

- Rename `Shape::BezPathIter` to `ElementsIter`
- Rename `Shape::to_bez_path` to `elements`
- Rename `Shape::into_bez_path` to `to_path` (and maybe also change `self` to `&self`?)
- Add a provided method `fn segments(&self, tolerance: f64) -> Segments<Self::ElementsIter> { ... }` to `Shape`
- Add a freestanding method `fn segments<I>(elements: I) -> Segments<I::IntoIter> where I: IntoIterator<Item = PathEl> { ... }`
- Either implement `BezPath::segments` in terms of `Shape::segments` or remove it

**Comment by cmyr** [comment]
generally this looks good to me. Agree that `to_path` should be `&self`.

would bikeshed `segments` and `elements` a bit; the alternative I would imagine are `path_segments` and `path_elements`. My thinking here is that the relationship between a shape and a bezier path is not necessarily obvious? In any case I could imagine either version but want to at least discuss it.

Another thing to discuss is separating out `segments(&self, tolerance: f64)` into `segments(&self)` and `segments_with_tolerance(&self, tolerance: f64)`, where the first calls the second with a reasonable value; we could do the same for `elements()`. Another alternative would be to provide a `DEFAULT_TOLERANCE` associated const to `Shape`, and mention it in the docs. (I find the tolerance arguments to be a paper-cut, and I a likely source of errors).

**Comment by raphlinus** [comment]
Hm, it's embarrassing, there's some unfinished business regarding `into_bez_path`. The trait method exists because it was meant to support this method on `BezPath`:

```rust
    fn into_bez_path(self, _tolerance: f64) -> BezPath {
        self
    }
```

That's why it's self, to avoid allocating. The `to_bez_path` method already exists and has somewhat different ownership behavior. When GAT lands, then `Self::BezPathIter` can take a reference to the BezPath (with lifetime), which would let it iterate without allocating.

**Comment by laurmaedje** [comment]
Then maybe we could have both `to_path` and `into_path` with `into_path` having a default impl in terms of `to_path`, which can be overriden for `BezPath`?

Regarding the name, I agree, `path_segments` or maybe `to_path_segments` (analogously to `to_path`) would be good.

Regarding the tolerance: Even with the `DEFAULT_TOLERANCE`, we would still need both `segments` and `segments_with_tolerance`, right? Because sometimes you want to decide tolerance at the call-site. Here, it would really be nice if rust had default arguments ...

**Comment by raphlinus** [comment]
> Then maybe we could have both `to_path` and `into_path` with `into_path` having a default impl in terms of `to_path`, which can be overriden for `BezPath`?

That is the current state, modulo the implementation being missing (and the names). I don't have a lot of insight into why; my best excuse is that I was waiting to see if the GAT situation would stabilize, then never got around to coming back to it.

**Comment by laurmaedje** [comment]
The small difference is that the proposed `to_path` would actually return a `BezPath` and not an iterator. The iterator would be produced by `to_path_elements` and that's the only mandatory method, then.

**Comment by raphlinus** [comment]
> Regarding the tolerance: Even with the `DEFAULT_TOLERANCE`, we would still need both `segments` and `segments_with_tolerance`, right? Because sometimes you want to decide tolerance at the call-site. Here, it would really be nice if rust had default arguments ...

I know, right? I guess I have a different feeling about this than Colin, I feel it's a bit like a noisy clippy lint. What's the right value for this? Are you rendering? Are you doing scientific calculations? Will the result be scaled after the fact? There's no one right answer, so having the parameter makes you think. And not having multiple variants that do almost the same thing also feels cleaner to me. But this is *totally* a style question, and I'm not going to block if there's consensus otherwise.

**Comment by raphlinus** [comment]
Got it. Let me see if I can summarize:

|               |  to_path_elements   |    to_path    |   into_path  |
|---------------|---------------------|---------------|--------------|
| BezPath       |  clones             |    clones     |   zero cost  |
| Simple shapes |  iterates           |    allocates  |   allocates  |

And then if we can put lifetimes into associated types:

|               |  to_path_elements   |    to_path    |   into_path  |
|---------------|---------------------|---------------|--------------|
| BezPath       |  ***iterates***             |    clones     |   zero cost  |
| Simple shapes |  iterates           |    allocates  |   allocates  |

**Comment by laurmaedje** [comment]
Yes, this looks right to me. If we're fine with that, I'd have a stab at implementing this tomorrow. The two remaining questions are:
- Remove `BezPath::segments` or keep it. I don't really have a strong opinion, here.
- Whether to have the with-tolerance and without-tolerance variants. I tend to agree with [this](https://github.com/linebender/kurbo/issues/136#issuecomment-700285848) (having just the one with tolerance), but ultimately I think both are fine, it's just that a general decision needs to be made for the crate.

**Comment by raphlinus** [comment]
If `BezPath::segments` is replaced by a version that takes `IntoIterator` rather than a slice, that seems to me to take care of all reasonable use cases. I certainly don't have any attachment to the current signature, and there are comments suggesting I was still trying to figure out the best API :)

**Comment by cmyr** [comment]
I'm happy to have the `tolerance` argument be required, but I would like us to provide better guidance around picking an appropriate tolerance. I see us as having two main potential users: people doing graphics, and people doing serious numerical work. For the latter, I think it's fine that we expect them to pick a tolerance, but for the former I think it would be nice to provide some more guidance, such as a `DEFAULT_TOLERANCE` argument.

I'm happy to just have a single `segments` (and `elements`) method, that takes a tolerance, but to try and make it easier for the user to pick an appropriate value somehow.

**Comment by raphlinus** [comment]
Sure. I'd be happy to come up with some language, as the tradeoff is probably not very clear to users who are not hardcore implementers of 2D graphics libraries :)

**Comment by laurmaedje** [comment]
> If `BezPath::segments` is replaced by a version that takes `IntoIterator` rather than a slice, that seems to me to take care of all reasonable use cases. I certainly don't have any attachment to the current signature, and there are comments suggesting I was still trying to figure out the best API :)

That definitely applies to the private `BezPath::segments_of_slice`. However, I just realized that it probably still makes sense to keep the public `BezPath::segments` because it can omit the tolerance parameter (in contrast to the generic `Shape` impl) and it can be chained (in contrast to the freestanding `segments`). So it's kind of similar to `BezPath::flatten`.
