### ISSUE TITLE
inv_arclen broken/changed in 0.8.1

### ISSUE THREAD

**Issue by RazrFalcon** [linebender/kurbo#176]
```rust
let c = kurbo::CubicBez::from_points(0.2, 0.73, 0.35, 1.08, 0.85, 1.08, 1.0, 0.73);
println!("{}", c.inv_arclen(0.5, 0.5));
```

- 0.8.0 returns 0.4926965024447632
- 0.8.1 returns 0.25

**Comment by cmyr** [comment]
This will be related to #173. @raphlinus?

**Comment by raphlinus** [comment]
This doesn't seem like a bug to me. I locally added this test, and it works fine:

```rust

    #[test]
    fn cubicbez_inv_arclen_accuracy() {
        let c = CubicBez::new((0.2, 0.73), (0.35, 1.08), (0.85, 1.08), (1.0, 0.73));
        let true_t = c.inv_arclen(0.5, 1e-12);
        for i in 1..12 {
            let accuracy = (0.1f64).powi(i);
            let approx_t = c.inv_arclen(0.5, accuracy);
            assert!((approx_t - true_t).abs() <= accuracy);
        }
    }
```

If @RazrFalcon's tests are triggering whenever the values are changing at all, even if they're inside the given accuracy, that suggests to me that the tests are too brittle. It's also suspicious to me that there's an accuracy parameter that's unreasonably high. My goal is to provide algorithms that are quite fast even for reasonably high accuracy. But part of serving that goal is to make accuracy explicit, so you only pay for the accuracy you need.

**Comment by RazrFalcon** [comment]
Yes, this is an edge case where I have a small curve and scale it up like 100x times later.
On the other hand, it worked before just fine, so this is at least a breaking change.

The problem is that I'm not sure I would be able to apply the transform first in my case.
Maybe a fallback/legacy implementation should be preserved? Otherwise I guess I would have to simply copy-paste the old one to my codebase.

Here are my real world results:

0.8.0:

```
CubicBez { p0: (0.2, 0.73), p1: (0.35, 1.08), p2: (0.85, 1.08), p3: (1.0, 0.73) }
0.06588: 0.06491769116212198
0.20435999999999999: 0.20137491447922362
0.38915999999999995: 0.38347554178280807
0.56904: 0.5607280355023361
0.66792: 0.6581636958258125
0.73008: 0.7194157250097454
0.8336399999999999: 0.8214630245961048
0.9803999999999999: 0.9660793019936917
```

0.8.1:

```
CubicBez { p0: (0.2, 0.73), p1: (0.35, 1.08), p2: (0.85, 1.08), p3: (1.0, 0.73) }
0.06588: 0.132458845581061
0.20435999999999999: 0.20068745723961182
0.38915999999999995: 0.25
0.56904: 0.75
0.66792: 0.75
0.73008: 0.7597078625048727
0.8336399999999999: 0.8107315122980524
0.9803999999999999: 0.8830396509968458
```

As you can see, the precision dropped significantly.

**Comment by james-lawrence** [comment]
hate to necro bump but @RazrFalcon is it possible to unblock the kurbo version usvg depends on? druid seems locked on version 0.14.x and seems related to this issue. I've been trying to improve the SVG handling in druid but there are potentially a bunch of fixes in usvg.

**Comment by RazrFalcon** [comment]
Open an issue in resvg repo.
