### ISSUE TITLE
BezPath::contains returns incorrect results

### ISSUE THREAD

**Issue by Lunderberg** [linebender/kurbo#180]
## Description

The current implementation of `BezPath::contains` gives incorrect results in many cases.

## Environment

* Rustc - 1.52.0
* Kurbo - 0.8.1 (latest)

## Steps to Reproduce

Compile and run the example below as `main.rs`.  This compares against a different check of points being inside the triangle, though based on [the note on `PathSeg::intersect_line`](https://docs.rs/kurbo/0.8.1/kurbo/enum.PathSeg.html#method.intersect_line), this is not a reliable check.

```rust
use kurbo::{BezPath, Line, Point, Shape};

fn contains_count_intersections(path: &BezPath, point: Point) -> bool {
    let bbox = path.bounding_box();
    let outside_point = kurbo::Point::new(bbox.min_x() - 1.0, bbox.min_y());
    let line = Line::new(point, outside_point);
    let num_intersections = path
        .segments()
        .map(|seg| seg.intersect_line(line).len())
        .sum::<usize>();

    num_intersections % 2 != 0
}

fn main() {
    let mut path = BezPath::new();
    path.move_to((0.0, 0.0));
    path.line_to((1.0, 1.0));
    path.line_to((2.0, 0.0));
    path.close_path();

    let test_point = Point::new(1.0, 0.5);

    println!(
        "path.contains({}) = {}",
        test_point,
        path.contains(test_point),
    );
    println!(
        "contains_count_intersections({}) = {}",
        test_point,
        contains_count_intersections(&path, test_point),
    );
}
```

## Expected behavior

Program runs and outputs

```
path.contains((1, 0.5)) = true
contains_count_intersections((1, 0.5)) = true
```

## Observed behavior

Program runs and outputs

```
path.contains((1, 0.5)) = false
contains_count_intersections((1, 0.5)) = true
```

**Comment by raphlinus** [comment]
I think this is a confusion of signs in the line case of `winding_inner`. The fix might be as simple as changing `(...) * (sign as f64) >= 0.0` to `(...) * (sign as f64) <= 0.0`, but a proper PR would have more validation and at least this test.

**Comment by Lunderberg** [comment]
I can confirm, that sign change does solve the issues I'm seeing in a more complicated example as well.  The issues I was having were all within the bounding box of the line segments of the object outline.  In the examples below, the yellow regions are locations determined to be within the outline.


| `contains_count_intersection(point)` | <img src="https://user-images.githubusercontent.com/3888575/119241379-c0952900-bb0a-11eb-8e62-dd895c95f9d5.png" width=400> |
| ---- | ---- |
| `path.contains(point)` | <img src="https://user-images.githubusercontent.com/3888575/119241382-c559dd00-bb0a-11eb-8375-7c3a38832e57.png"  width=400> |
| `point.contains(point)`, with `<=` in `winding_inner` | <img src="https://user-images.githubusercontent.com/3888575/119241384-c723a080-bb0a-11eb-90ca-5a92656f0a48.png"  width=400> |

**Comment by raphlinus** [comment]
I still have this on my radar but it's not easy to allocate a chunk of time to create a proper test case. Perhaps it would make sense to get the sign change and a simple test case in now, and defer more careful tests to later.

**Comment by Lunderberg** [comment]
Thank you, and no worries at all!  The library is fantastic to use, and I wanted to give confirmation that the fix works in more than the trivial test case.

**Comment by raphlinus** [comment]
I was going to do a more careful test case, but figured it would be useful to get this in, especially as we're planning a release soon. Let me know if it works!
