### ISSUE TITLE
Interpolatable cubic-to-quadratic

### ISSUE THREAD

**Issue by simoncozens** [linebender/kurbo#192]
One facility which would be very useful (all right, *indispensable*) for font work is the ability to convert *multiple* cubic curves to quadratics together, with the guarantee that the returned curves have the same structure (same number of quadratics and, ideally, the same elidable "implied oncurves").

fontmake's [cu2qu](https://github.com/googlefonts/cu2qu/blob/main/Lib/cu2qu/cu2qu.py) has an algorithm with these guarantees; we could steal it, or do something clever ourselves.

**Comment by raphlinus** [comment]
This is an interesting problem for sure! I think it's possible to do better than cu2qu, but of course there are complex tradeoffs. I have no objection to making the cu2qu algorithm or something like it available (especially to make results that reproduce existing tools), but I am also interested in something that is more "interpolation compatible" by construction, and plan to spend some research time on it. I can move up the priority of that if it's starting to block production of variable fonts.

**Comment by yisibl** [comment]
Does something similar to this function do?https://docs.rs/lyon/0.11.0/lyon/algorithms/geom/cubic_to_quadratic/fn.cubic_to_quadratics.html

**Comment by raphlinus** [comment]
Not very similar, as that function takes *one* cubic, and the method here takes a slice of cubics, mapping them to a sequence of quadratic b-splines that are "interpolation compatible." This is really something extremely specialized to the production of variable fonts.
