### ISSUE TITLE
Ambiguous license

### ISSUE THREAD

**Issue by mwcampbell** [linebender/kurbo#207]
The top level of the repository has files for both the MIT and Apache licenses, suggesting dual licensing. But `src/lib.rs` indicates only the Apache license. I would prefer dual licensing, since I can't use any dependency that's solely under the Apache license in the core of [AccessKit](https://github.com/AccessKit/accesskit).

**Comment by raphlinus** [comment]
It is dual MIT + Apache, and I agree that the notice in the source files is unclear. I would happily accept a PR that clarified the license strings in the files. I think one good model for this might be the newer files in piet-gpu, for example [stages.rs](https://github.com/linebender/piet-gpu/blob/master/piet-gpu/src/stages.rs).

**Comment by derekdreery** [comment]
Does having the license text at the top of each file make a difference legally? If not I think it's better to only include it in lib.rs.

**Comment by derekdreery** [comment]
I propose changing the preamble in `lib.rs` to "Copyright 2018-2023 The kurbo Authors

You may use this library according to the MIT license or the Apache license version 2.0 at your discretion. Copies of both licenses are included with this crate on GitHub and `crates.io`."

and closing this issue once that change has been made. Does anyone disagree with this.

**Comment by raphlinus** [comment]
My personal feeling is that we can converge on a standard policy across linebender.

Each file has this header:

```
// Copyright <year of file creation> the kurbo Authors
// SPDX-License-Identifier: Apache-2.0 OR MIT
```

I believe this is rigorous (especially in cases where there may be multiple licenses in a repo, likely less a problem for kurbo) and not too invasive.

**Comment by xStrom** [comment]
I think having a standard policy of that short header is fine.

I am slightly wondering about the capitalization though. Having *the* not capitalized follows title capitalization rules I guess. However for the name, at least for Xilem, Vello, Glazier - it would be capitalized. Is kurbo going to remain lower case?

**Comment by raphlinus** [comment]
This has come up before. I used lowercase as it refers to the crate name. I don't have a super strong feeling, I think we can flip a coin as long as we're consistent.

**Comment by xStrom** [comment]
Alright, in the case of kurbo that can work. With others there can be multiple crates per repo (like Druid has) so for having a unified header per repo I think going with the (capitalized) project name would be better. Then based on that I would also advocate the same choice for kurbo, just so the header format is consistent across linebender.

I'll volunteer to do the grunt work and submit the PR soon, both for kurbo and other repos.
