### ISSUE TITLE
Use `sin_cos` for slightly faster computation

### ISSUE THREAD

**Issue by derekdreery** [linebender/kurbo#209]
https://github.com/linebender/kurbo/blob/1ca29449bb4e654baa45ee7f9b901d642c1efc1d/src/affine.rs#L69

`sin` and `cos` are calculated using some expansion or other (I assume Taylor series?). There exists a method `f64::sin_cos` that calculates both at the same time, saving a few numeric operations. Using this function here and anywhere else you need both results will result in a slight speedup.

**Comment by Davvy42** [comment]
Need 120000
