### ISSUE TITLE
Add asserts in debug mode to detect invalid BezPath construction as early as possible.

### ISSUE THREAD

**Issue by ctrlcctrlv** [linebender/kurbo#212]
Cf. #211 re more `BezPath` bugginess.

**Comment by cmyr** [comment]
This is interesting. In practice yes, but there is maybe room for more clarity here. If a `BezPath` contains only (say) a single `LineTo(x, y)` element, converting it to segments will return an empty list.

So more concretely, I believe that a `BezPath` should always start with a `MoveTo`, and if it doesn't then there may be unexpected behaviour. Specifically, the first point will end up being treated like a `MoveTo`.

I'm not sure exactly how we should handle this. Certainly we could improve documentation. We might also benefit (in general) from a `BezPathBuilder` type, which would create with a starting point.

**Comment by raphlinus** [comment]
A BezPath without an initial `MoveTo` is a bug. We don't have a lot of validation of this sort of thing right now, but I would be open to doing more as, for example, debug asserts. The documentation should also clearly specify the invariants. Right now, it basically says "PostScript-style" which does imho imply this, but it could be stated a lot more explicitly.

**Comment by derekdreery** [comment]
I checked the docs and it already says that each subpath must begin with a `MoveTo`. So I think the actionable here is to look at all the ways a `BezPath` can be created or modified and when in debug_assertions check that the `MoveTo` invariant is upheld. I think that would be enough to close the issue. Does anyone disagree?

**Comment by ctrlcctrlv** [comment]
I think that would help a lot @derekdreery. I think we could also use a short doc for people building their own, as I must, just laying out what we can and can't do. Also understanding that those in my situation may not know all of the maths behind all of kurbo.

**Comment by raphlinus** [comment]
There is a change I would like to make though, which is allowing a new subpath (after a `ClosePath`) to begin without a new `MoveTo`, and the start point is the same as the end point of the previous subpath. This makes it match SVG and PDF semantics. I still think starting a path without `MoveTo` should be considered invalid.

**Comment by ctrlcctrlv** [comment]
I don't but that's fair. You're entitled to that. We use `MoveTo` in MFEK to decide Closed/Open state.

**Comment by ctrlcctrlv** [comment]
(Probably because we're so fonts-focused, not general-purpose like kurbo. I'm sure you know but neither CFF nor glyf even allow for open paths. The `PointType::Move` we have is special and is elided at export.)

**Comment by cmyr** [comment]
I'll look into adding some `debug_assert!`s in various places to alert the user of missing `MoveTo`s.

**Comment by derekdreery** [comment]
We discussed this at office hours. We decided that in all cases we can add `debug_assert` checks to catch invalid `BezPath`s early, but that we should also look at relaxing some of the restrictions to make `BezPath`'s behavior less suprising. The next step is for someone (me?) to check exactly what those invariants are.

**Comment by cmyr** [comment]
afaict this is closed by #247, feel free to reopen if I've misunderstood.
