### ISSUE TITLE
Add Rounded line

### ISSUE THREAD

**Issue by TornaxO7** [linebender/kurbo#246]
There is [RoundedRect](https://docs.rs/kurbo/0.9.1/kurbo/struct.RoundedRect.html) but no `RoundedLine`. Would be nice, if this could be added.

**Comment by raphlinus** [comment]
Is that a [stadium](https://en.wikipedia.org/wiki/Stadium_(geometry))? It doesn't seem to be a standard element of any geometry library I know of, and many of its use cases can be handled by a rounded rect in which the minor dimension is equal to twice the rounding radius.

**Comment by TornaxO7** [comment]
> Is that a [stadium](https://en.wikipedia.org/wiki/Stadium_(geometry))?

I think yes.

>  It doesn't seem to be a standard element of any geometry library I know of, and many of its use cases can be handled by a rounded rect in which the minor dimension is equal to twice the rounding radius.

Well you're right. I'll close this issue then. Sorry!
