### ISSUE TITLE
Breaking change: `scale_non_uniform` arguments go from `f64, f64` to `Vec2`

### ISSUE THREAD

**Issue by derekdreery** [linebender/kurbo#249]
How would people feel about changing the arguments for `Affine::scale_non_uniform`, so the signature would go from `scale_non_uniform(cx: f64, cy: f64)` to `scale_non_uniform(c: Vec2)`?

It would be a breaking change, but geometrically it feels like a Vec2 is the right object to represent a scale.

**Comment by dfrg** [comment]
If we were going to do something like this, my preference would be to change `scale` to take `impl Into<Vec2>` and then add `From<f64> for Vec2` (essentially a broadcast conversion). I believe this would not be a breaking change and would allow us to deprecate `scale_non_uniform`. 

But I’m not sure that I agree with `Vec2` being an appropriate type to represent a scale in this library. If we didn’t already have a strong semantic distinction between vectors and points it would make more sense.

**Comment by derekdreery** [comment]
Hmm, I'm not sure about overloading `Affine::scale`, so perhaps it's best to close this ticket.

**Comment by derekdreery** [comment]
Since there are no other comments I will close.
