### ISSUE TITLE
What would prevent `kurbo` from using `euclid`'s `Point2D`?

### ISSUE THREAD

**Issue by kud1ing** [linebender/kurbo#26]
https://github.com/kud1ing/rust_graphics_wiki/blob/master/drawing_data_types.md#point-vector

**Comment by kud1ing** [comment]
Ah, they were added only recently: https://github.com/linebender/kurbo/commit/4ac0373c442215b99f30ef30bfcd4b53b4c01795

**Comment by cmyr** [comment]
We explored using euclid directly but there was consensus that it was too heavyweight, so we've gone with our own impls for these types. If needed, conversion functions could be provided behind a feature flag.

For some background, see #17.

**Comment by kud1ing** [comment]
Hm, i see. For the records this is about compilation time and not code size?
`euclid` compiles in 12 secs on my 5 year old laptop.

**Comment by cmyr** [comment]
There was also the problem that we can't trivially add methods to types from external crates, and GUI programming generally benefits from lots of little helper methods that are missing in euclid, so we'd end up needing some kind of wrapper type anyway. But 12 seconds of additional overhead certainly adds up as well.

**Comment by kud1ing** [comment]
Fair enough, thanks.
