### ISSUE TITLE
Concerns around impl From<((f64, f64), (f64, f64))> for Rect

### ISSUE THREAD

**Issue by cmyr** [linebender/kurbo#29]
This is currently implemented, and I think that it is likely to be misused.

A rect can be constructed from a pair of points or from a point and a size. There is no way to know from this implementation which behaviour to expect.

I think it would be reasonable to have a conversion between `Rect` and `(f64, f64, f64, f64)`, cooresponding to `(minx, miny, maxx, maxy)`, but I think `((f64, f64), (f64, f64))`, if implemented, should default to (`origin`, `size`), but the fact that there's any room for confusion makes me feel that it should be removed.

**Comment by raphlinus** [comment]
Totally fine with me to remove this.

**Comment by cmyr** [comment]
unfortunately it's a breaking change..

**Comment by raphlinus** [comment]
Move fast and break things, that's my current motto.
