### ISSUE TITLE
Figure out sign conventions

### ISSUE THREAD

**Issue by raphlinus** [linebender/kurbo#4]
One of the current points of confusion is whether the coordinate system is y-up or y-down. The former is more conventional in math, the latter completely standard in graphics these days (though this was less true, PostScript was y-up, as are fonts to this day).

Related issues are conventions around whether a positive area shape is clockwise or withershins, and whether a clockwise circle has positive or negative signed curvature. The winding number should match area - it should be positive if the point is inside a positive area shape. Either convention will do, but it should be consistent.

Another thing that falls in the same category is the convention of `Vec2::cross`. The right hand rule says right ^ up = 1, but is up (0, 1) or (0, -1)? For this, I think we pick one and document it.

I do think kurbo is interesting in both math and graphics contexts. For methods like `Vec2::from_angle` and `Affine::rotate` it's hard to just pick a convention, so I'm inclined to split them into `_y_up` and `_y_down` variants, so that the user makes an explicit choice. For the signed area stuff, I'm not sure there's a strong convention; e^{iπt} is anticlockwise in a y-up coordinate space as t increases. Do people know of other conventions we can follow? Something along the lines of https://github.com/JuliaLang/julia/issues/8750 which surveys rounding conventions of many languages might be a model.

Tagging @behdad @jrus @pomax @nical @Connicpu @kvark as they might have horses in this race.

**Comment by Pomax** [comment]
Call me crazy, but if the idea is, basically, "the best library" then it feels like there should be a way to bootstrap the coordinate system so that after calling the appropriate function, the library "just works" using whatever convention it should be using. And then whether that takes the form of a static call, or per-call option, or even literally a duplicated library with the two different y conventions should probably be informed by "what performs best".

**Comment by raphlinus** [comment]
@Pomax I'm open to that, but want to make sure it doesn't come at a significant cost of compile time, usability, doc clarity, etc.

Sketching this out, here are a couple ways this might look:

One is to have a zero-size type for Y direction, then instead of `Affine` and `Vec2` you have `Affine<YUp>` and `Vec2<YDown>`. You might have `From` conversions that flip the sign of y as well, so you can interop. However, I fear that this might be really bad for ergonomics - I think the user would get annoyed frequently having to constantly specify this explicitly.

Another possibility is to do this at the module level: instead of `use kurbo::{Affine, Vec2}` as now, write `use kurbo::y_up::{Affine, Vec2}`. Internally that might be implemented as above.

I see the value, it feels more correct, but I'm hesitating. It's really only a small handful of methods (essentially rotations) where you might really want both conventions, and for the other stuff, as long as it's documented, users will be adapt and be happy, I think.

[MathWorld](http://mathworld.wolfram.com/PolygonArea.html) defines positive area as counterclockwise, and then of course gives the shoelace formula assuming y-up. Looking at [Cairo](http://gtk-rs.org/docs/cairo/struct.Context.html#method.rectangle), which was designed by people I trust, they define a rectangle as clockwise (given width and height of the same sign).

So this is where I'm leaning right now, though quite open to discussion:

The convention of y-up or y-down is not specified. Positive area is widdershins in a y-up space, clockwise in y-down. I'm inclined to define theta the same way (a clockwise rotation in y-down), but I see [Cairo's rotate](http://gtk-rs.org/docs/cairo/struct.Context.html#method.rotate) and probably other things define it as anticlockwise, so in that case I'll have separate rotate_y_up and rotate_y_down methods.

Curvature and winding number are consistent with area: the curvature of a smooth convex path of positive area is positive, and the winding number inside a positive area path is positive. The shoelace formula as conventionally written, in xy coordinates, has the correct sign.

**Comment by behdad** [comment]
I suggest defining things in terms of X/Y sign and agnostic of Y direction: when traveling in the direction of the positive X axis, then turning towards positive Y axis is a positive angle, positive curvature, results in positive area, and winding number.

**Comment by behdad** [comment]
Right. The most commonly type is done wrong in a y-up model is to model rectangle's y with it's "top", and positive y height towards y-down... Most other shapes are intuitive.

**Comment by nical** [comment]
> Now I think the main challenge is documentation and naming; you certainly don't want to call the maximal y coordinate of a bounding box rectangle "bottom,"

Right. We have a couple of these naming issues in euclid, which doesn't matter for servo/gecko work but other users tend to be opinionated about these things and there's been complaints.

**Comment by jrus** [comment]
Rotation is a bivector-valued quantity. The most straight-forward convention is for + to be x∧y, irrespective of which way y is pointing.

**Comment by jrus** [comment]
Another place where conventions often differ is when describing a rectangle (e.g. bounding box), should the order be [*x*<sub>0</sub>, *x*<sub>1</sub>, *y*<sub>0</sub>, *y*<sub>1</sub>] or [*x*<sub>0</sub>, *y*<sub>0</sub>, *x*<sub>1</sub>, *y*<sub>1</sub>]. Both are common, and the inconsistency is annoying.

* * *

Even more obnoxiously, when dealing with matrices, Matlab (and other tools) often use the mathematics convention that the first index represents columns and the second index represents rows, however when plotting an array of data in a 2d graphical picture they extend that to the awful convention of plotting the first index vertically and the second index horizontally, i.e. in (*y*, *x*) order, with *y* from left to right and *x* from top to bottom. But then of course they switch the convention around when working with a ≥3-dimensional array, where the first index goes back to meaning *x*. Bleh.

**Comment by raphlinus** [comment]
I do want to get this right, and think the above PR is a step in the right direction.

Consensus on renaming `cross` to `wedge`?

**Comment by kvark** [comment]
@behdad agreed, also relevant - https://github.com/kvark/mint/issues/32

**Comment by raphlinus** [comment]
[MathWorld](http://mathworld.wolfram.com/CrossProduct.html) has this as cross product with the × notation. The sense I get is that the current naming is appropriate, but I could add proper bivector operations at some point.

**Comment by behdad** [comment]
> [MathWorld](http://mathworld.wolfram.com/CrossProduct.html) has this as cross product with the × notation. The sense I get is that the current naming is appropriate, but I could add proper bivector operations at some point.

Correct.  The two are related but separate concepts.

https://en.wikipedia.org/wiki/Exterior_algebra

**Comment by kud1ing** [comment]
As mentioned on Zulip, i've started a sketch of documents e.g. https://github.com/kud1ing/rust_graphics_wiki/blob/master/coordinate_system.md that could be inspiration for RFC-like documents on https://github.com/linebender/wiki where the current problems and insights are easier to follow.

**Comment by kud1ing** [comment]
I've opened a PR to the wiki with a file discussing this/giving an overview: https://github.com/linebender/wiki/pull/2
