### ISSUE TITLE
Add Point::integral, Size::integral, Rect::integral etc

### ISSUE THREAD

**Issue by cmyr** [linebender/kurbo#40]
Not sure if this makes sense for other types, but possibly. These are useful when dealing with drawing to ensure that you're on pixel boundaries.

**Comment by raphlinus** [comment]
I'm not sure I 100% understand the signature. Are these basically variants of round?

I agree with the need for these, but want to make sure we get them right. Also, keep in mind (more of a druid issue than piet/kurbo) that in almost all cases we have vectors in px units but we have a dpi scale factor that gets us to device pixels; thus we might want to make methods that take an additional scale parameter, and do something roughly equivalent to `round(vec * scale) / scale`.

**Comment by cmyr** [comment]
yea, these are probably just `f64::round` under the hood.

**Comment by raphlinus** [comment]
I'd rather call the types "round" then. For Rect, I think we want "expand_integral" (open to other names) which does floor of top/left and ceil of bottom/right. Probably shrink_integral too for symmetry, but the former is more useful for bbox calculations.

I *think* rounding the coordinates for layout is the Right Thing, but we need to think this stuff through carefully (for example, when there's nested layout, do you round at each level).

**Comment by cmyr** [comment]
Sounds good. I would be open to just using `integral` and not providing the `shrink` variant.
