### ISSUE TITLE
Add missing (commutative) Mul impls

### ISSUE THREAD

**Issue by cmyr** [linebender/kurbo#41]
There are a bunch of places where we have code like,
```rust
impl Mul<Line> for Affine {
    type Output = Line;

    #[inline]
    fn mul(self, other: Line) -> Line {
        Line {
            p0: self * other.p0,
            p1: self * other.p1,
        }
    }
}
```

Without also having `impl Mul<Affine> for Line`. This means  that `affine * line` works but `line * affine` doesn't, which is a papercut.

**Comment by raphlinus** [comment]
Missing "line * affine" is intentional, matrix multiplication is in general not commutative.

**Comment by cmyr** [comment]
okay, I'm probably holding it wrong.
