### ISSUE TITLE
Arc::from_svg_arc and Arc::to_cubic_beziers are broken again

### ISSUE THREAD

**Issue by RazrFalcon** [linebender/kurbo#51]
It was fixed in https://github.com/linebender/kurbo/pull/16, but after updating from 0.2.3 to 0.5.1 it broke down again.

SVG path: `M 100 100 h 25 a 25 25 0 1 0 -25 25 z`

**Comment by raphlinus** [comment]
I can into this, but could you give a little more detail what's wrong? Ideally there should be tests for it - I know kurbo is a bit thin on tests, but this is evidence they would be useful.

**Comment by RazrFalcon** [comment]
I've tried to write a test, but there are no Eq, approx_eq or to_string methods to compare segments.

Here is a minimal example:

```rust
let path = BezPath::from_svg("M 100 100 h 25 a 25 25 0 1 0 -25 25 z").unwrap();
println!("{:#?}", path);
```

It produces:

```
M 100.0, 100.0
L 125.0, 100.0
C 125.0, 113.80711874576983, 86.19288125423017, 75.0, 100.0, 75.0
C 113.80711874576984, 75.0, 75.0, 113.80711874576983, 75.0, 100.0
C 75.0, 86.19288125423016, 113.80711874576983, 125.0, 100.0, 125.0
Z
```

But it should be:

```
M 100 100 
L 125 100 
C 125 86.19288125423 113.80711874577 75 100 75 
C 86.19288125423 75 75 86.19288125423 75 100 
C 75 113.80711874577 86.19288125423 125 100 125 
Z
```

|Expected|Actual|
---|---
|![out2](https://user-images.githubusercontent.com/725494/62871357-0614a780-bd24-11e9-97b2-0a9a65e483ba.png)|![out](https://user-images.githubusercontent.com/725494/62871363-09a82e80-bd24-11e9-9a11-bf6a6ea71a04.png)|

**Comment by raphlinus** [comment]
One way to write a test is to measure expected area and perimeter, possibly also winding number at select points. In any case, much clearer what's going wrong now, thanks.

**Comment by raphlinus** [comment]
By git bisection, I've narrowed this down to #18, which is not surprising, as it did a substantial refactor.
