### ISSUE TITLE
Add contains(Point) fn to shape, with default impl

### ISSUE THREAD

**Issue by cmyr** [linebender/kurbo#70]
This would be 100% about ergonomics.

Motivated by https://github.com/xi-editor/druid/pull/231. Checking whether a point is inside some shape is going to be a very common task when doing UI development, and the current way to do this is not very discoverable; `winding` is a term that many people (myself included) may not be aware of or notice when they're thinking about hit-testing.

My idea would be to add a method to `shape`, with the signature

```rust
trait Shape {
    fn contains(&self, point: Point) -> bool {
        let winding = self.winding(point);
        winding != 0 && winding.singum() == self.area().signum() as i32
    }
}
```

I suspect there may be reasons I haven't thought of that make this not a good idea, in which case an alternative would be to just add a `contains()` method to a few important shapes like `Rect` and `Circle`. (edit: I see this already exists on `Rect`...)

**Comment by raphlinus** [comment]
I'm not understanding all the complexity around area signum here. The behavior gets interesting in, say, a figure-8 shape, where there are regions of both positive and negative winding; the sign of the area will depend on which is larger. I'd be perfectly happy for `contains` to just be `winding() != 0`.

I don't remember in detail, but it's possible the collision between a `Shape` trait method and the concrete method on `Rect` is why I didn't have this already. It's entirely possible it will provoke a (tiny) semver bump. In any case, I don't think it's a requirement to have specialized impls; the blanket impl based on winding should be fine.

Agree this is an ergonomics issue.

**Comment by cmyr** [comment]
oh yea I'm totally overthinking things with the `signum`.

This shouldn't need to be a version bump; code will always default to the inherent(?) impl, even if the trait is in scope, so existing code will work as normal. If you want to call the trait method, you will need to do `Shape::contains(&my_rect, point)`.

Aside: the only ergonomics downside to this is that it requires the trait to be in scope, which can be frustrating sometimes.
