### ISSUE TITLE
Add non-uniform scale `Affine`

### ISSUE THREAD

**Issue by DerLando** [linebender/kurbo#79]
Hello, the (quite new) `arcs` [crate](https://github.com/Michael-F-Bryan/arcs) is using `kurbo` as a dependency. I want to implement basic transformations based on `Affine`. What seems to be missing is a *non-uniform-scale* constructor.

```rust
#[inline]
pub const fn scale_non_uniform(s_x: f64, s_y: f64) -> Affine {
    Affine([s_x, 0.0, 0.0, s_y, 0.0, 0.0])
}
```

It would be nice to be able to call this *"natively"* from kurbo instead of doing it in the `arcs` crate.

Is this something you would add to `kurbo`? I can also issue a pull request but like some feedback on naming and implementation first, as I'm not too familiar with `kurbo`

**Comment by raphlinus** [comment]
I think this is fine.

**Comment by DerLando** [comment]
Thank you!

This is resolved in https://github.com/linebender/kurbo/pull/80
