### ISSUE TITLE
CubicBezier.arclen exhibits pathological behaviour when passed a bezier curve which is just a point

### ISSUE THREAD

**Issue by HalfVoxel** [linebender/kurbo#99]
When passed a bezier curve in which all control points are identical then the est_gauss9_error method will always return NaN and the function will recursively subdivide the curve 16 times. This leads to 2^16 = 65536 evaluations of the `rec` function which is very very slow (comparatively).

The method should check for degenerate bezier curves before trying to calculate the length of them.

**Comment by raphlinus** [comment]
Agree. Should be a fairly easy fix? PR welcome!

**Comment by HalfVoxel** [comment]
Will fix!
